# Generated by Django 4.1.6 on 2023-02-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in progress', 'В процессе'), ('made', 'Сделано')], max_length=40, verbose_name='Статус')),
                ('created_at', models.DateField(verbose_name='Дата выполнения')),
            ],
        ),
    ]
