# Generated by Django 4.1.6 on 2023-02-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0004_alter_todo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(default='new', max_length=1000, verbose_name='Описание'),
        ),
    ]
