# Generated by Django 4.1.6 on 2023-02-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0005_alter_todo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in progress', 'В процессе'), ('made', 'Сделано')], default='new', max_length=40, verbose_name='Статус'),
        ),
    ]
